### ISSUE TITLE
Accessing to Mongoid model charts gives NoMethodError: undefined method `group'

### ISSUE THREAD

**Issue by SuperMasterBlasterLaser** [pgeraghty/rails_admin_charts#11]
I have added your gem into my gemfile an run bundle.

Then I included into my Mongoid Document.

When I try to access yo charts, it gives me NoMethodError in RailsAdmin::Main#charts undefined method `group' for Item:Class

**Comment by pgeraghty** [comment]
MongoDB does not support the `GROUP BY` SQL clause, so you'd have to add replacement methods to your model to override `total_records_since` and `delta_records_since`.

I believe you'd have to use Mongoid's Map/Reduce DSL, see [here](http://docs.mongodb.org/manual/applications/aggregation/) for more information.

**Comment by SuperMasterBlasterLaser** [comment]
Can you please write example of overriding.

**Comment by pgeraghty** [comment]
Can't help you with Mongoid, but to replace the default chart data (total records) you can use this annotated method as a guide (add it to your model). You need to replace the lines starting with `totals =` and `before_count =` with lines that pull the required info from Mongoid.

``` ruby
    def total_records_since(since = 30.days.ago)
      # generate a hash of totals for each date
      # (where the key is the date and the value is the total number of records created on that date)
      # for example:
      totals = { Date.parse('2015-07-29') => 2, Date.parse('2015-07-30') => 3, Date.parse('2015-07-31') => 1 }

      # count all the records before the "since" date parameter and provide that in another local variable
      # for example:
      before_count = 10

      # leave this line intact and it will generate the data for the graph
      (since.to_date..Date.today).each_with_object([]) { |day, a| a << (a.last || before_count) + (totals[day] || totals[day.to_s] || 0) }
    end
```

**Comment by SuperMasterBlasterLaser** [comment]
Please add something about Mongoid in your Instructions. There are a lot of Mongoid users which have chosen rails_admin and If some of them wanted to add your charts?

**Comment by SuperMasterBlasterLaser** [comment]
I have changed your code to this:

```
  def total_records_since(since = 30.days.ago)

    days_between = (Date.today - since.to_date).to_i

     totals = Hash.new(0)
     days_between.times do |s|
      totals[(Date.today - s.days).to_date] = self.where(:created_at.gte => Date.today - s.days, :created_at.lt => Date.today - (s - 1).days).count
     end

      before_count = self.where(:created_at.lte => Date.today - days_between.days).count

     (since.to_date..Date.today).each_with_object([]) { |day, a| a << (a.last || before_count) + (totals[day] || totals[day.to_s] || 0) }
  end
```

Now I CAN show mongoid elements by your charts.

However, I think your `(since.to_date..Date.today).each_with_object([]) { |day, a| a << (a.last || before_count) + (totals[day] || totals[day.to_s] || 0) }` creates wrong data. I have 18 elements created in one day and it shows me that I have created 18 in every last five day.
